name: Compile

on:
  workflow_dispatch:

# on:
#   schedule:
#     - cron: '20 1,13 * * *'

jobs:

  update:
    name: Update tzdata
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js latest
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Install dependencies
        run: npm ci

      - id: step1
        name: Check for updates
        run: echo "RESULT=$(npm run check)" >> $GITHUB_OUTPUT

      - name: Update tzdata
        if: steps.step1.outputs.RESULT == "Update available"
        run: npm run compile

      - name: Commit changes
        if: steps.step1.outputs.RESULT == "Update available"
        uses: stefanzweifel/git-auto-commit-action@v5
