name: CI tests

on:
  push:
    branches:
      - master
      - develop
      - release*
      - gtz
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Use the latest version of Node.js, plus the 3 most recent LTS lines
        node-version:
          - latest
          - lts/*
          - lts/-1
          - lts/-2 # Probably EOL depending on release schedules, but still good to test

    steps:
      - uses: actions/checkout@v7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
